openapi: 3.0.3
info:
  title: Django DRF medi_track
  version: 0.0.0
paths:
  /available-slots/{doctor_id}/{day}/:
    get:
      operationId: available_slots_retrieve
      parameters:
      - in: path
        name: day
        schema:
          type: string
        required: true
      - in: path
        name: doctor_id
        schema:
          type: integer
        required: true
      tags:
      - available-slots
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /book-appointment/{doctor_id}/:
    post:
      operationId: book_appointment_create
      parameters:
      - in: path
        name: doctor_id
        schema:
          type: integer
        required: true
      tags:
      - book-appointment
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /cancel-appointment/{appointment_id}/:
    delete:
      operationId: cancel_appointment_destroy
      parameters:
      - in: path
        name: appointment_id
        schema:
          type: integer
        required: true
      tags:
      - cancel-appointment
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /department-list-by-hospital/{hospital_id}/:
    get:
      operationId: department_list_by_hospital_retrieve
      parameters:
      - in: path
        name: hospital_id
        schema:
          type: integer
        required: true
      tags:
      - department-list-by-hospital
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /doctor-detal/{doctor_id}/:
    get:
      operationId: doctor_detal_retrieve
      parameters:
      - in: path
        name: doctor_id
        schema:
          type: integer
        required: true
      tags:
      - doctor-detal
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /doctors-list-by-department/{department_id}/:
    get:
      operationId: doctors_list_by_department_retrieve
      parameters:
      - in: path
        name: department_id
        schema:
          type: integer
        required: true
      tags:
      - doctors-list-by-department
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /doctors-list-by-hospital/{hospital_id}/:
    get:
      operationId: doctors_list_by_hospital_retrieve
      parameters:
      - in: path
        name: hospital_id
        schema:
          type: integer
        required: true
      tags:
      - doctors-list-by-hospital
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /hospital-list/:
    get:
      operationId: hospital_list_retrieve
      tags:
      - hospital-list
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /list-patient-appointments/:
    get:
      operationId: list_patient_appointments_retrieve
      tags:
      - list-patient-appointments
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /login/:
    post:
      operationId: login_create
      tags:
      - login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserTokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserTokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserTokenObtainPair'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTokenObtainPair'
          description: ''
  /medi_track/schema/:
    get:
      operationId: medi_track_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - medi_track
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /patient-register/:
    post:
      operationId: patient_register_create
      tags:
      - patient-register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Patient'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Patient'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
          description: ''
components:
  schemas:
    Admin:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
      - username
    BlankEnum:
      enum:
      - ''
    GenderEnum:
      enum:
      - Male
      - Female
      - Other
      type: string
      description: |-
        * `Male` - Male
        * `Female` - Female
        * `Other` - Other
    NullEnum:
      enum:
      - null
    Patient:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          $ref: '#/components/schemas/Admin'
        name:
          type: string
          nullable: true
          maxLength: 255
        dob:
          type: string
          format: date
          nullable: true
        gender:
          nullable: true
          oneOf:
          - $ref: '#/components/schemas/GenderEnum'
          - $ref: '#/components/schemas/BlankEnum'
          - $ref: '#/components/schemas/NullEnum'
        phone_number:
          type: string
          nullable: true
          maxLength: 255
      required:
      - id
      - user
    UserTokenObtainPair:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
