# Generated by Django 5.0.3 on 2024-04-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_patient_gender_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department',
            new_name='department_and_hospital',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital',
        ),
    ]
