# Generated by Django 5.0.3 on 2024-04-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_department_doctor_department_and_hospital_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='department_and_hospital',
            new_name='hospital_department_and',
        ),
    ]
