# Generated by Django 5.0.3 on 2024-04-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_hospital_department_and_doctor_hospital_and_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.CharField(default='100', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
