# Generated by Django 5.0.3 on 2024-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_appointment_hospital_appointment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_patient',
            field=models.BooleanField(default=False, verbose_name='patient status'),
        ),
    ]
